### ISSUE TITLE
Nested loops

### ISSUE THREAD

**Issue by DeanKamali** [donavon/lloop#1]
Hi 
I'm able to use `SimpleLoop` here to loop over `alerts`.
```
{userInfo.map( patient => {
  console.log(userInfo);
  //  patient.profile.alerts.map(alert => console.log(alert));
return (
  <SimpleLoop items={patient.profile.alerts}>
    <li />
  </SimpleLoop>
    )
  }
)}
```
However I haven't been able to incorporate `ItemLoop` to loop over `userInfo` "Array of objects"

```
<ItemLoop items={userInfo} primaryKey="patient">
    <SimpleLoop items={item}>
            <li />
     </SimpleLoop>
</ItemLoop>
```

Keep getting `Uncaught ReferenceError: item is not defined`

Can I use `SimpleLoop`  and `ItemLoop` Interchangeably?

**Comment by donavon** [comment]
Take a llook at this example. https://codesandbox.io/s/xj5kp1ryvz

As you can see, the "inner" loop needs to be within it's own component as it needs to extract the `alerts` array. Hope this helps. Sorry for the delay in responding.

**Comment by DeanKamali** [comment]
Thanks @donavon , I appreciate your example, helped clean my code quite a bit, I'm also using `Render if` component, keep up the good work :)
